# Site settings
url: http://dangerisgo.com
title: Danger is Go!
subtitle:
author: Cameron Wardzala
simple_search: #http://google.com/search
description:
excerpt_link: More

subscribe_rss: http://feeds.feedburner.com/DangerIsGo

sass:
    style: compressed

twitter_username: camwardzala
github_username:  cwardzala

titlecase: true

permalink: /blog/:year/:month/:day/:title.html

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: cwardzala
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: camwardzala
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: dangerisgo
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-3833224-1

# Facebook Like
facebook_like: true
